#ifndef _MYWINAPI_OPENFOLDERANDSELECTITEM_H
#define _MYWINAPI_OPENFOLDERANDSELECTITEM_H

#include <Windows.h>

EXTERN_C
HRESULT __stdcall
OpenFolderAndSelectItem(LPCTSTR szPath);

#endif/*_MYWINAPI_OPENFOLDERANDSELECTITEM_H*/
